"""create lockers and locker_slots

Revision ID: 286855093ad1
Revises: 
Create Date: 2026-05-08 13:35:30.146227

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '286855093ad1'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lockers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locker_slots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('locker_id', sa.UUID(), nullable=False),
    sa.Column('size', sa.Enum('XS', 'S', 'M', 'L', 'XL', name='slot_size'), nullable=False),
    sa.Column('is_occupied', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['locker_id'], ['lockers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locker_slots_locker_id'), 'locker_slots', ['locker_id'], unique=False)
    op.create_index(op.f('ix_locker_slots_size'), 'locker_slots', ['size'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_locker_slots_size'), table_name='locker_slots')
    op.drop_index(op.f('ix_locker_slots_locker_id'), table_name='locker_slots')
    op.drop_table('locker_slots')
    op.drop_table('lockers')
    # ### end Alembic commands ###
