"""create parcels

Revision ID: 539ca13f220d
Revises: 286855093ad1
Create Date: 2026-05-08 14:19:01.688596

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '539ca13f220d'
down_revision: str | None = '286855093ad1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parcels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sender', sa.String(length=255), nullable=False),
    sa.Column('receiver', sa.String(length=255), nullable=False),
    sa.Column(
        'size',
        postgresql.ENUM('XS', 'S', 'M', 'L', 'XL', name='slot_size', create_type=False),
        nullable=False,
    ),
    sa.Column('state', sa.Enum('CREATED', 'ASSIGNED', 'IN_LOCKER', 'PICKED_UP', 'EXPIRED', 'CANCELLED', name='parcel_state'), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['slot_id'], ['locker_slots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcels_size'), 'parcels', ['size'], unique=False)
    op.create_index(op.f('ix_parcels_slot_id'), 'parcels', ['slot_id'], unique=False)
    op.create_index(op.f('ix_parcels_state'), 'parcels', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parcels_state'), table_name='parcels')
    op.drop_index(op.f('ix_parcels_slot_id'), table_name='parcels')
    op.drop_index(op.f('ix_parcels_size'), table_name='parcels')
    op.drop_table('parcels')
    # ### end Alembic commands ###
